# ó - \u00f3
app.addr = localhost:8080
app.title = Strona g\u0142\u00f3wna
app.addAccount = Dodaj u\u017Cytkownika
app.administratorPage = Strona g\u0142\u00f3wna administratora
app.userPage = Strona g\u0142\u00f3wna u\u017Cytkonika
app.createEvent = Utw\u00f3rz spotkanie
app.manageEvent = Zarz\u0105dzaj spotkaniem
app.registerEvent = Zapisz si\u0119 na spotkanie
app.findEvent = Znajd\u017A spotkanie
app.findAccount = Znajd\u017A u\u017Cytkownika
app.cancel = Anuluj
app.delete = Usu\u0144

index.mainPage = Strona g\u0142\u00f3wna

menu.login = Zaloguj

login.username = Login:
login.password = Has\u0142o:
login.rememberme = Zapami\u0119taj mnie
login.adduser = Dodaj u\u017cytkownika
login.login = Zaloguj do facebooka
login.logout = Wyloguj
login.error = Z\u0142y login lub has\u0142o

addUser.login = Login: 
addUser.password = Has\u0142o: 
addUser.repeatPassword = Powt\u00f3rz has\u0142o:
addUser.role = Typ u\u017cytkownika:
addUser.equalPassword = Podane has\u0142a musz\u0105 si\u0119 zgadza\u0107!
addUser.userExists = U\u017cytkownik istnieje!

event.lp = Lp
event.name = Nazwa spotkania
event.nameASC = Nazwa spotkania \u21e7
event.nameDESC = Nazwa spotkania \u21e9
event.description = Opis spotkania
event.location = Miejsce
event.locationASC = Miejsce \u21e7
event.locationDESC = Miejsce \u21e9
event.duration = D\u0142ugo\u015B\u0107 [min]
event.creationDate = Czas utworzenia
event.creationDateASC = Czas utworzenia \u21e7
event.creationDateDESC = Czas utworzenia \u21e9
event.startDate = Data rozpocz\u0119cia
event.startTimestamp = Czas rozpocz\u0119cia 
event.endDate = Data zako\u0144czenia
event.endTimestamp = Czas zako\u0144czenia
event.username = Nazwa u\u017Cytkownika
event.usernameASC = U\u017Cytkownik \u21e7
event.usernameDESC = U\u017Cytkownik \u21e9
event.contact = Kontakt
event.contactASC = Kontakt/E-mail \u21e7
event.contactDESC = Kontakt/E-mail \u21e9
event.createEvent = Utw\u00f3rz spotkanie
event.findEvent = Znajd\u017A spotkanie
event.sortEvent = Posortuj spotkania
event.deleteEvent = Usu\u0144 spotkanie
event.registerEvent = Zapisz sie na spotkanie
event.type = Rodzaj spotkania
event.userEvent = Moje spotkania

account.lp = Lp
account.findAccount = Znajd\u017A u\u017Cytkownika
account.username = Nazwa
account.usernameASC = Login \u21e7
account.usernameDESC = Login \u21e9
account.contact = Kontakt/E-mail
account.registerDate = Data rejestracji
account.registerDateASC = Data rejestracji \u21e7
account.registerDateDESC = Data rejestracji \u21e9
account.lastLogin = Ostatnie logowanie
account.register = Zarejestruj si\u0119
account.details = Dane konta
account.password = Has\u0142o:
account.repeatPassword = Powt\u00f3rz has\u0142o:
account.newPassword = Nowe has\u0142o:

error.eventNotFound = Nie ma takiego spotkania lub zosta\u0142o usuni\u0119te!
error.startDateIsPast = Data rozpocz\u0119cia musi by\u0107 w przysz\u0142o\u015Bci!
error.endDateIsPast = Data zako\u0144czenia musi by\u0107 w przysz\u0142o\u015Bci!
error.startAfterEnd = Data rozpocz\u0119cia musi by\u0107 wcze\u015Bniej ni\u017C data zako\u0144czenia!

schedule = Utw\u00f3rz plan zaj\u0119\u0107
schedule.download = Pobierz w formacie XML
schedule.submit = Prze\u015Blij

Pattern.event.duration=D\u0142ugo\u015B\u0107 spotkania musi by\u0107 wyra\u017Cona w minutach!
Future.event.startDate=Podana data musi by\u0107 w przysz\u0142o\u015Bci!
Future.event.endDate=Podana data musi by\u0107 w przysz\u0142o\u015Bci!
Pattern.event.startTimestamp=Musisz poda\u0107 prawid\u0142ow\u0105 godzin\u0119 (0:00 - 23:59)!
Pattern.event.endTimestamp=Musisz poda\u0107 prawid\u0142ow\u0105 godzin\u0119 (0:00 - 23:59)!
Pattern.event.startDate=Musisz poda\u0107 dat\u0119 rozpocz\u0119cia (rrrr-mm-dd)
Pattern.event.endDate=Musisz poda\u0107 dat\u0119 zako\u0144czenia (rrrr-mm-dd)